### ISSUE TITLE
Flooded robots cause NullPointerException

### ISSUE THREAD

**Issue by j-mao** [battlecode/battlecode20#254]
May be related to #221; unsure. Cause not fully investigated.
Full game details in dev chat (source code / submission ids not provided here because taken from scrimmage).
```
java.lang.NullPointerException
	at battlecode.world.GameWorld.destroyRobot(GameWorld.java:708)
	at battlecode.world.GameWorld.setFloodStatus(GameWorld.java:419)
	at battlecode.world.GameWorld.floodfill(GameWorld.java:644)
	at battlecode.world.GameWorld.processEndOfRound(GameWorld.java:607)
	at battlecode.world.GameWorld.runRound(GameWorld.java:128)
	at battlecode.server.Server.runMatch(Server.java:248)
	at battlecode.server.Server.run(Server.java:165)
	at battlecode.server.Main.runHeadless(Main.java:77)
	at battlecode.server.Main.run(Main.java:109)
	at battlecode.server.Main.main(Main.java:119)
```

**Comment by arvid220u** [comment]
fixed by f537db5984f50ffbdca9c00ffee57487cb3f86d4
